import { Code } from "./code"
import { Key } from "./key"

export interface Bank {
  key: Key
  code: Code
  name: string
  shortName: string
  bin: string
  vietQRStatus: number
  lookupSupported?: number
  swiftCode?: string | null
}

export enum VietQRStatus {
  NOT_SUPPORTED = -1,
  RECEIVE_ONLY = 0,
  TRANSFER_SUPPORTED = 1
}

export const BanksObject: Record<Key, Bank> = {
  [Key.ABBANK]: {
    key: Key.ABBANK,
    code: Code.ABBANK,
    name: 'Ngân hàng TMCP An Bình',
    bin: '970425',
    shortName: 'AB Bank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'ABBKVNVX',
  },
  [Key.ACB]: {
    key: Key.ACB,
    code: Code.ACB,
    name: 'Ngân hàng TMCP Á Châu',
    bin: '970416',
    shortName: 'ACB',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'ASCBVNVX',
  },
  [Key.AGRIBANK]: {
    key: Key.AGRIBANK,
    code: Code.AGRIBANK,
    name: 'Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam',
    bin: '970405',
    shortName: 'Agribank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'VBAAVNVX',
  },
  [Key.BAC_A_BANK]: {
    key: Key.BAC_A_BANK,
    code: Code.BAC_A_BANK,
    name: 'Ngân hàng TMCP Bắc Á',
    bin: '970409',
    shortName: 'BacA Bank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'NASCVNVX',
  },
  [Key.BAOVIET_BANK]: {
    key: Key.BAOVIET_BANK,
    code: Code.BAOVIET_BANK,
    name: 'Ngân hàng TMCP Bảo Việt',
    bin: '970438',
    shortName: 'BaoViet Bank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'BVBVVNVX',
  },
  [Key.BANVIET]: {
    key: Key.BANVIET,
    code: Code.BANVIET,
    name: 'Ngân hàng TMCP Bản Việt',
    bin: '970454',
    shortName: 'BVBank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'VCBCVNVX',
  },
  [Key.BIDC]: {
    key: Key.BIDC,
    code: Code.BIDC,
    name: 'Ngân hàng TMCP Đầu tư và Phát triển Campuchia',
    bin: '',
    shortName: 'BIDC',
    vietQRStatus: VietQRStatus.NOT_SUPPORTED
  },
  [Key.BIDV]: {
    key: Key.BIDV,
    code: Code.BIDV,
    name: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam',
    bin: '970418',
    shortName: 'BIDV',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'BIDVVNVX'
  },
  [Key.CAKE]: {
    key: Key.CAKE,
    code: Code.CAKE,
    name: 'Ngân hàng số CAKE by VPBank - Ngân hàng TMCP Việt Nam Thịnh Vượng',
    bin: '546034',
    shortName: 'CAKE by VPBank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: null
  },
  [Key.CBBANK]: {
    key: Key.CBBANK,
    code: Code.CBBANK,
    name: 'Ngân hàng Thương mại TNHH MTV Xây dựng Việt Nam',
    bin: '970444',
    shortName: 'CB Bank',
    vietQRStatus: VietQRStatus.RECEIVE_ONLY,
    lookupSupported: 1,
    swiftCode: 'GTBAVNVX',
  },
  [Key.CIMB]: {
    key: Key.CIMB,
    code: Code.CIMB,
    name: 'Ngân hàng TNHH MTV CIMB Việt Nam',
    bin: '422589',
    shortName: 'CIMB Bank',
    vietQRStatus: VietQRStatus.RECEIVE_ONLY,
    lookupSupported: 1,
    swiftCode: 'CIBBVNVN',
  },
  [Key.COOP_BANK]: {
    key: Key.COOP_BANK,
    code: Code.COOP_BANK,
    name: 'Ngân hàng Hợp tác xã Việt Nam',
    bin: '970446',
    shortName: 'Co-op Bank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: null,
  },
  [Key.DBS_BANK]: {
    key: Key.DBS_BANK,
    code: Code.DBS_BANK,
    name: 'NH TNHH MTV Phát triển Singapore - Chi nhánh TP. Hồ Chí Minh',
    bin: '796500',
    shortName: 'DBS Bank',
    vietQRStatus: VietQRStatus.RECEIVE_ONLY,
    lookupSupported: 0,
    swiftCode: 'DBSSVNVX',
  },
  [Key.DONG_A_BANK]: {
    key: Key.DONG_A_BANK,
    code: Code.DONG_A_BANK,
    name: 'Ngân hàng TMCP Đông Á',
    bin: '970406',
    shortName: 'DongA Bank',
    vietQRStatus: VietQRStatus.RECEIVE_ONLY,
    lookupSupported: 1,
    swiftCode: 'EACBVNVX',
  },
  [Key.EXIMBANK]: {
    key: Key.EXIMBANK,
    code: Code.EXIMBANK,
    name: 'Ngân hàng TMCP Xuất Nhập khẩu Việt Nam',
    bin: '970431',
    shortName: 'Eximbank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'EBVIVNVX'
  },
  [Key.GPBANK]: {
    key: Key.GPBANK,
    code: Code.GPBANK,
    name: 'Ngân hàng Thương mại TNHH MTV Dầu Khí Toàn Cầu',
    bin: '970408',
    shortName: 'GPBank',
    vietQRStatus: VietQRStatus.RECEIVE_ONLY,
    lookupSupported: 1,
    swiftCode: 'GBNKVNVX',
  },
  [Key.HDBANK]: {
    key: Key.HDBANK,
    code: Code.HDBANK,
    name: 'Ngân hàng TMCP Phát triển TP. Hồ Chí Minh',
    bin: '970437',
    shortName: 'HDBank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'HDBCVNVX'
  },
  [Key.HONGLEONG_BANK]: {
    key: Key.HONGLEONG_BANK,
    code: Code.HONGLEONG_BANK,
    name: 'Ngân hàng TNHH MTV Hong Leong Việt Nam',
    bin: '970442',
    shortName: 'HongLeong Bank',
    vietQRStatus: VietQRStatus.RECEIVE_ONLY,
    lookupSupported: 1,
    swiftCode: 'HLBBVNVX',
  },
  [Key.HSBC]: {
    key: Key.HSBC,
    code: Code.HSBC,
    name: 'Ngân hàng TNHH MTV HSBC (Việt Nam)',
    bin: '458761',
    shortName: 'HSBC Vietnam',
    vietQRStatus: VietQRStatus.RECEIVE_ONLY,
    lookupSupported: 1,
    swiftCode: 'HSBCVNVX'
  },
  [Key.IBK_HCM]: {
    key: Key.IBK_HCM,
    code: Code.IBK_HCM,
    name: 'Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh TP. Hồ Chí Minh',
    bin: '970456',
    shortName: 'IBK HCM',
    vietQRStatus: VietQRStatus.RECEIVE_ONLY,
    lookupSupported: 0,
    swiftCode: null,
  },
  [Key.IBK_HN]: {
    key: Key.IBK_HN,
    code: Code.IBK_HN,
    name: 'Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh Hà Nội',
    bin: '970455',
    shortName: 'IBK HN',
    vietQRStatus: VietQRStatus.RECEIVE_ONLY,
    lookupSupported: 0,
    swiftCode: null,
  },
  [Key.INDOVINA_BANK]: {
    key: Key.INDOVINA_BANK,
    code: Code.INDOVINA_BANK,
    name: 'Ngân hàng TNHH Indovina',
    bin: '970434',
    shortName: 'Indovina Bank',
    vietQRStatus: VietQRStatus.RECEIVE_ONLY,
    lookupSupported: 1,
    swiftCode: null
  },
  [Key.KASIKORN_BANK]: {
    key: Key.KASIKORN_BANK,
    code: Code.KASIKORN_BANK,
    name: 'Ngân hàng Đại chúng TNHH KASIKORNBANK - CN TP. Hồ Chí Minh',
    bin: '668888',
    shortName: 'Kasikornbank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'KASIVNVX'
  },
  [Key.KIENLONG_BANK]: {
    key: Key.KIENLONG_BANK,
    code: Code.KIENLONG_BANK,
    name: 'Ngân hàng TMCP Kiên Long',
    bin: '970452',
    shortName: 'KienlongBank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'KLBKVNVX'
  },
  [Key.KOOKMIN_BANK_HCM]: {
    key: Key.KOOKMIN_BANK_HCM,
    code: Code.KOOKMIN_BANK_HCM,
    name: 'Ngân hàng Kookmin - Chi nhánh TP. Hồ Chí Minh',
    bin: '970463',
    shortName: 'Kookmin Bank HCM',
    vietQRStatus: VietQRStatus.RECEIVE_ONLY,
    lookupSupported: 0,
    swiftCode: null
  },
  [Key.KOOKMIN_BANK_HN]: {
    key: Key.KOOKMIN_BANK_HN,
    code: Code.KOOKMIN_BANK_HN,
    name: 'Ngân hàng Kookmin - Chi nhánh Hà Nội',
    bin: '970462',
    shortName: 'Kookmin Bank HN',
    vietQRStatus: VietQRStatus.RECEIVE_ONLY,
    lookupSupported: 0,
    swiftCode: null
  },
  [Key.LIENVIETPOST_BANK]: {
    key: Key.LIENVIETPOST_BANK,
    code: Code.LIENVIETPOST_BANK,
    name: 'Ngân hàng TMCP Bưu Điện Liên Việt',
    bin: '970449',
    shortName: 'LienVietPostBank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'LVBKVNVX',
  },
  [Key.MBBANK]: {
    key: Key.MBBANK,
    code: Code.MBBANK,
    name: 'Ngân hàng TMCP Quân đội',
    bin: '970422',
    shortName: 'MB Bank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'MSCBVNVX'
  },
  [Key.MSB]: {
    key: Key.MSB,
    code: Code.MSB,
    name: 'Ngân hàng TMCP Hàng Hải',
    bin: '970426',
    shortName: 'MSB',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'MCOBVNVX',
  },
  [Key.NAM_A_BANK]: {
    key: Key.NAM_A_BANK,
    code: Code.NAM_A_BANK,
    name: 'Ngân hàng TMCP Nam Á',
    bin: '970428',
    shortName: 'Nam A Bank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'NAMAVNVX',
  },
  [Key.NCB]: {
    key: Key.NCB,
    code: Code.NCB,
    name: 'Ngân hàng TMCP Quốc Dân',
    bin: '970419',
    shortName: 'NCB Bank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'NVBAVNVX',
  },
  [Key.NONGHYUP_BANK_HN]: {
    key: Key.NONGHYUP_BANK_HN,
    code: Code.NONGHYUP_BANK_HN,
    name: 'Ngân hàng Nonghyup - Chi nhánh Hà Nội',
    bin: '801011',
    shortName: 'Nonghyup Bank',
    vietQRStatus: VietQRStatus.RECEIVE_ONLY,
    lookupSupported: 0,
    swiftCode: null
  },
  [Key.OCB]: {
    key: Key.OCB,
    code: Code.OCB,
    name: 'Ngân hàng TMCP Phương Đông',
    bin: '970448',
    shortName: 'OCB Bank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'ORCOVNVX',
  },
  [Key.OCEANBANK]: {
    key: Key.OCEANBANK,
    code: Code.OCEANBANK,
    name: 'Ngân hàng Thương mại TNHH MTV Đại Dương',
    bin: '970414',
    shortName: 'Ocean Bank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'OCBKUS3M',
  },
  [Key.PGBANK]: {
    key: Key.PGBANK,
    code: Code.PGBANK,
    name: 'Ngân hàng TMCP Xăng dầu Petrolimex',
    bin: '970430',
    shortName: 'PG Bank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'PGBLVNVX'
  },
  [Key.PUBLIC_BANK]: {
    key: Key.PUBLIC_BANK,
    code: Code.PUBLIC_BANK,
    name: 'Ngân hàng TNHH MTV Public Việt Nam',
    bin: '970439',
    shortName: 'Public Bank Vietnam',
    vietQRStatus: VietQRStatus.RECEIVE_ONLY,
    lookupSupported: 1,
    swiftCode: 'VIDPVNVX',
  },
  [Key.PVCOM_BANK]: {
    key: Key.PVCOM_BANK,
    code: Code.PVCOM_BANK,
    name: 'Ngân hàng TMCP Đại Chúng Việt Nam',
    bin: '970412',
    shortName: 'PVcomBank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'WBVNVNVX',
  },
  [Key.SACOMBANK]: {
    key: Key.SACOMBANK,
    code: Code.SACOMBANK,
    name: 'Ngân hàng TMCP Sài Gòn Thương Tín',
    bin: '970403',
    shortName: 'Sacombank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'SGTTVNVX'
  },
  [Key.SAIGONBANK]: {
    key: Key.SAIGONBANK,
    code: Code.SAIGONBANK,
    name: 'Ngân hàng TMCP Sài Gòn Công Thương',
    bin: '970400',
    shortName: 'SaigonBank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'SBITVNVX',
  },
  [Key.SCB]: {
    key: Key.SCB,
    code: Code.SCB,
    name: 'Ngân hàng TMCP Sài Gòn',
    bin: '970429',
    shortName: 'SCB',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'SACLVNVX',
  },
  [Key.SEA_BANK]: {
    key: Key.SEA_BANK,
    code: Code.SEA_BANK,
    name: 'Ngân hàng TMCP Đông Nam Á',
    bin: '970440',
    shortName: 'SeABank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'SEAVVNVX'
  },
  [Key.SHB]: {
    key: Key.SHB,
    code: Code.SHB,
    name: 'Ngân hàng TMCP Sài Gòn - Hà Nội',
    bin: '970443',
    shortName: 'SHB',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'SHBAVNVX',
  },
  [Key.SHINHAN_BANK]: {
    key: Key.SHINHAN_BANK,
    code: Code.SHINHAN_BANK,
    name: 'Ngân hàng TNHH MTV Shinhan Việt Nam',
    bin: '970424',
    shortName: 'Shinhan Bank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'SHBKVNVX'
  },
  [Key.STANDARD_CHARTERED_BANK]: {
    key: Key.STANDARD_CHARTERED_BANK,
    code: Code.STANDARD_CHARTERED_BANK,
    name: 'Ngân hàng TNHH MTV Standard Chartered Bank Việt Nam',
    bin: '970410',
    shortName: 'Standard Chartered Vietnam',
    vietQRStatus: VietQRStatus.RECEIVE_ONLY,
    lookupSupported: 1,
    swiftCode: 'SCBLVNVX'
  },
  [Key.TECHCOMBANK]: {
    key: Key.TECHCOMBANK,
    code: Code.TECHCOMBANK,
    name: 'Ngân hàng TMCP Kỹ thương Việt Nam',
    bin: '970407',
    shortName: 'Techcombank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'VTCBVNVX'
  },
  [Key.TIMO]: {
    key: Key.TIMO,
    code: Code.TIMO,
    name: 'Ngân hàng số Timo by Bản Việt Bank',
    bin: '963388',
    shortName: 'Timo',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 0,
    swiftCode: null,
  },
  [Key.TPBANK]: {
    key: Key.TPBANK,
    code: Code.TPBANK,
    name: 'Ngân hàng TMCP Tiên Phong',
    bin: '970423',
    shortName: 'TPBank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'TPBVVNVX',
  },
  [Key.UBANK]: {
    key: Key.UBANK,
    code: Code.UBANK,
    name: 'Ngân hàng số Ubank by VPBank - Ngân hàng TMCP Việt Nam Thịnh Vượng',
    bin: '546035',
    shortName: 'Ubank by VPBank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: null
  },
  [Key.UNITED_OVERSEAS_BANK]: {
    key: Key.UNITED_OVERSEAS_BANK,
    code: Code.UNITED_OVERSEAS_BANK,
    name: 'Ngân hàng United Overseas Bank Việt Nam',
    bin: '970458',
    shortName: 'United Overseas Bank Vietnam',
    vietQRStatus: VietQRStatus.RECEIVE_ONLY,
    lookupSupported: 1,
    swiftCode: null
  },
  [Key.VIB]: {
    key: Key.VIB,
    code: Code.VIB,
    name: 'Ngân hàng TMCP Quốc tế Việt Nam',
    bin: '970441',
    shortName: 'VIB',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'VNIBVNVX',
  },
  [Key.VIET_A_BANK]: {
    key: Key.VIET_A_BANK,
    code: Code.VIET_A_BANK,
    name: 'Ngân hàng TMCP Việt Á',
    bin: '970427',
    shortName: 'VietABank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'VNACVNVX'
  },
  [Key.VIET_BANK]: {
    key: Key.VIET_BANK,
    code: Code.VIET_BANK,
    name: 'Ngân hàng TMCP Việt Nam Thương Tín',
    bin: '970433',
    shortName: 'VietBank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'VNTTVNVX',
  },
  [Key.VIETCOMBANK]: {
    key: Key.VIETCOMBANK,
    code: Code.VIETCOMBANK,
    name: 'Ngân hàng TMCP Ngoại Thương Việt Nam',
    bin: '970436',
    shortName: 'Vietcombank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'BFTVVNVX'
  },
  [Key.VIETINBANK]: {
    key: Key.VIETINBANK,
    code: Code.VIETINBANK,
    name: 'Ngân hàng TMCP Công thương Việt Nam',
    bin: '970415',
    shortName: 'VietinBank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'ICBVVNVX',
  },
  [Key.VPBANK]: {
    key: Key.VPBANK,
    code: Code.VPBANK,
    name: 'Ngân hàng TMCP Việt Nam Thịnh Vượng',
    bin: '970432',
    shortName: 'VPBank',
    vietQRStatus: VietQRStatus.TRANSFER_SUPPORTED,
    lookupSupported: 1,
    swiftCode: 'VPBKVNVX',
  },
  [Key.VRB]: {
    key: Key.VRB,
    code: Code.VRB,
    name: 'Ngân hàng Liên doanh Việt - Nga',
    bin: '970421',
    shortName: 'VietNgaBank',
    vietQRStatus: VietQRStatus.RECEIVE_ONLY,
    lookupSupported: 1,
    swiftCode: null,
  },
  [Key.WOORI_BANK]: {
    key: Key.WOORI_BANK,
    code: Code.WOORI_BANK,
    name: 'Ngân hàng TNHH MTV Woori Việt Nam',
    bin: '970457',
    shortName: 'Woori Bank',
    vietQRStatus: VietQRStatus.RECEIVE_ONLY,
    lookupSupported: 1,
    swiftCode: null
  }
}

export const Banks: Bank[] = Object.values(BanksObject)